"""update tasks_categories_table

Revision ID: ecf8941ac6db
Revises: 411ffb6496d3
Create Date: 2022-04-25 01:41:22.544112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecf8941ac6db'
down_revision = '411ffb6496d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks_categories', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks_categories', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks_categories', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks_categories', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
